/**
 * MetricsNarrativeOverview - Sectioned natural-language overview generated by an LLM.
 */

import { Box, Paper, Typography } from '@mui/material';
import ReactMarkdown from 'react-markdown';
import type { MetricsInsightsPayload } from '../../types/metrics';

interface MetricsNarrativeOverviewProps {
  /**
   * LLM-generated insight payload.
   *
   * Expected shape:
   * - narrative_markdown: markdown string with section headings and bullets
   * - selection_metadata: optional thresholds and candidate counts
   */
  insights: MetricsInsightsPayload | null | undefined;
}

export function MetricsNarrativeOverview({ insights }: MetricsNarrativeOverviewProps) {
  if (!insights) {
    return null;
  }

  const hasNarrative: boolean =
    typeof insights.narrative_markdown === 'string' &&
    insights.narrative_markdown.trim().length > 0;

  if (!hasNarrative) {
    return null;
  }

  return (
    <Paper
      elevation={0}
      sx={{
        p: 2.5,
        mb: 2,
        border: '1px solid',
        borderColor: 'divider',
        borderRadius: 2,
        bgcolor: '#F8FAFC',
      }}
    >
      <Box sx={{ mb: 1 }}>
        <Typography variant="h6" sx={{ fontWeight: 600 }}>
          Overview Insights
        </Typography>
      </Box>

      <Box
        sx={{
          '& h2': { fontSize: '1rem', mt: 1.5, mb: 0.75 },
          '& ul': { mt: 0.5, mb: 1.25, pl: 2.25 },
          '& li': { mb: 0.35 },
          '& p': { mb: 1 },
        }}
      >
        <ReactMarkdown>{insights.narrative_markdown}</ReactMarkdown>
      </Box>
    </Paper>
  );
}

export default MetricsNarrativeOverview;

